service: comments-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - https://nickcellino.com
        - http://localhost:8080
      allowedHeaders:
        - hx-trigger
        - hx-target
        - hx-request
        - hx-current-url
      allowedMethods:
        - GET
        - POST

functions:

  comments-api:
    handler: index.handler
    environment:
      LAMBDA_BASE_URL: !Join ["", ["https://", !Ref HttpApi, ".execute-api.${aws:region}.amazonaws.com"]]
      ALLOWED_ORIGIN_URL: "http://localhost:8080"
      RECAPTCHA_SECRET: ${env:RECAPTCHA_SECRET}
      RECAPTCHA_SITEKEY: "6LcMAZQhAAAAAJKuFrianjr-xP8XIOysos4qeR4S"
    events:
      - httpApi:
          method: '*'
          path: /{proxy+}

